app = "ftc-platform-mcp"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  MCP_PORT = "3001"

[[services]]
  internal_port = 3001
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/health"

[deploy]
  strategy = "rolling"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512